package database

import (
	"database/sql"

	log "github.com/sirupsen/logrus"

	"github.com/pinpox/megaclan3000/internal/steamclient"
)

// GetUserStatsForGame returns a UserStatsForGame object by fetching the values from
// the database using a prepared statement.
func (ds *DataStorage) GetUserStatsForGame(steamID string) (steamclient.UserStatsForGame, error) {

	usfg := steamclient.UserStatsForGame{}
	var err error

	if rows, err := ds.statements["select_player_extra"].Query(steamID); err == nil {
		for rows.Next() {
			rows.Scan(
				&usfg.SteamID,
				&usfg.Extra.TotalKD,
				&usfg.Extra.LastMatchKD,
				&usfg.Extra.HitRatio,
				&usfg.Extra.PlayedHours,
			)
		}
	} else {
		return usfg, err
	}

	if rows, err := ds.statements["select_player_stats"].Query(steamID); err == nil {
		for rows.Next() {
			rows.Scan(

				&usfg.SteamID,

				&usfg.Stats.GILessonBombSitesA,
				&usfg.Stats.GILessonBombSitesB,
				&usfg.Stats.GILessonCsgoCycleWeaponsKb,
				&usfg.Stats.GILessonCsgoHostageLeadToHrz,
				&usfg.Stats.GILessonCsgoInstrExplainBombCarrier,
				&usfg.Stats.GILessonCsgoInstrExplainBuyarmor,
				&usfg.Stats.GILessonCsgoInstrExplainBuymenu,
				&usfg.Stats.GILessonCsgoInstrExplainFollowBomber,
				&usfg.Stats.GILessonCsgoInstrExplainInspect,
				&usfg.Stats.GILessonCsgoInstrExplainPickupBomb,
				&usfg.Stats.GILessonCsgoInstrExplainPlantBomb,
				&usfg.Stats.GILessonCsgoInstrExplainPreventBombPickup,
				&usfg.Stats.GILessonCsgoInstrExplainReload,
				&usfg.Stats.GILessonCsgoInstrExplainZoom,
				&usfg.Stats.GILessonCsgoInstrRescueZone,
				&usfg.Stats.GILessonDefusePlantedBomb,
				&usfg.Stats.GILessonFindPlantedBomb,
				&usfg.Stats.GILessonTrExplainPlantBomb,
				&usfg.Stats.GILessonVersionNumber,
				&usfg.Stats.LastMatchContributionScore,
				&usfg.Stats.LastMatchCtWins,
				&usfg.Stats.LastMatchDamage,
				&usfg.Stats.LastMatchDeaths,
				&usfg.Stats.LastMatchDominations,
				&usfg.Stats.LastMatchFavweaponID,
				&usfg.Stats.LastMatchFavweaponHits,
				&usfg.Stats.LastMatchFavweaponKills,
				&usfg.Stats.LastMatchFavweaponShots,
				&usfg.Stats.LastMatchGgContributionScore,
				&usfg.Stats.LastMatchKills,
				&usfg.Stats.LastMatchMaxPlayers,
				&usfg.Stats.LastMatchMoneySpent,
				&usfg.Stats.LastMatchMvps,
				&usfg.Stats.LastMatchRevenges,
				&usfg.Stats.LastMatchRounds,
				&usfg.Stats.LastMatchTWins,
				&usfg.Stats.LastMatchWins,
				&usfg.Stats.SteamStatMatchwinscomp,
				&usfg.Stats.SteamStatSurvivedz,
				&usfg.Stats.SteamStatXpearnedgames,
				&usfg.Stats.TotalBrokenWindows,
				&usfg.Stats.TotalContributionScore,
				&usfg.Stats.TotalDamageDone,
				&usfg.Stats.TotalDeaths,
				&usfg.Stats.TotalDefusedBombs,
				&usfg.Stats.TotalDominationOverkills,
				&usfg.Stats.TotalDominations,
				&usfg.Stats.TotalGgMatchesPlayed,
				&usfg.Stats.TotalGgMatchesWon,
				&usfg.Stats.TotalGunGameContributionScore,
				&usfg.Stats.TotalGunGameRoundsPlayed,
				&usfg.Stats.TotalGunGameRoundsWon,
				&usfg.Stats.TotalHitsAk47,
				&usfg.Stats.TotalHitsAug,
				&usfg.Stats.TotalHitsAwp,
				&usfg.Stats.TotalHitsBizon,
				&usfg.Stats.TotalHitsDeagle,
				&usfg.Stats.TotalHitsElite,
				&usfg.Stats.TotalHitsFamas,
				&usfg.Stats.TotalHitsFiveseven,
				&usfg.Stats.TotalHitsG3sg1,
				&usfg.Stats.TotalHitsGalilar,
				&usfg.Stats.TotalHitsGlock,
				&usfg.Stats.TotalHitsHkp2000,
				&usfg.Stats.TotalHitsM249,
				&usfg.Stats.TotalHitsM4a1,
				&usfg.Stats.TotalHitsMac10,
				&usfg.Stats.TotalHitsMag7,
				&usfg.Stats.TotalHitsMp7,
				&usfg.Stats.TotalHitsMp9,
				&usfg.Stats.TotalHitsNegev,
				&usfg.Stats.TotalHitsNova,
				&usfg.Stats.TotalHitsP250,
				&usfg.Stats.TotalHitsP90,
				&usfg.Stats.TotalHitsSg556,
				&usfg.Stats.TotalHitsSawedoff,
				&usfg.Stats.TotalHitsScar20,
				&usfg.Stats.TotalHitsSsg08,
				&usfg.Stats.TotalHitsTec9,
				&usfg.Stats.TotalHitsUmp45,
				&usfg.Stats.TotalHitsXm1014,
				&usfg.Stats.TotalKills,
				&usfg.Stats.TotalKillsAgainstZoomedSniper,
				&usfg.Stats.TotalKillsAk47,
				&usfg.Stats.TotalKillsAug,
				&usfg.Stats.TotalKillsAwp,
				&usfg.Stats.TotalKillsBizon,
				&usfg.Stats.TotalKillsDeagle,
				&usfg.Stats.TotalKillsElite,
				&usfg.Stats.TotalKillsEnemyBlinded,
				&usfg.Stats.TotalKillsEnemyWeapon,
				&usfg.Stats.TotalKillsFamas,
				&usfg.Stats.TotalKillsFiveseven,
				&usfg.Stats.TotalKillsG3sg1,
				&usfg.Stats.TotalKillsGalilar,
				&usfg.Stats.TotalKillsGlock,
				&usfg.Stats.TotalKillsHeadshot,
				&usfg.Stats.TotalKillsHegrenade,
				&usfg.Stats.TotalKillsHkp2000,
				&usfg.Stats.TotalKillsKnife,
				&usfg.Stats.TotalKillsKnifeFight,
				&usfg.Stats.TotalKillsM249,
				&usfg.Stats.TotalKillsM4a1,
				&usfg.Stats.TotalKillsMac10,
				&usfg.Stats.TotalKillsMag7,
				&usfg.Stats.TotalKillsMolotov,
				&usfg.Stats.TotalKillsMp7,
				&usfg.Stats.TotalKillsMp9,
				&usfg.Stats.TotalKillsNegev,
				&usfg.Stats.TotalKillsNova,
				&usfg.Stats.TotalKillsP250,
				&usfg.Stats.TotalKillsP90,
				&usfg.Stats.TotalKillsSawedoff,
				&usfg.Stats.TotalKillsScar20,
				&usfg.Stats.TotalKillsSg556,
				&usfg.Stats.TotalKillsSsg08,
				&usfg.Stats.TotalKillsTaser,
				&usfg.Stats.TotalKillsTec9,
				&usfg.Stats.TotalKillsUmp45,
				&usfg.Stats.TotalKillsXm1014,
				&usfg.Stats.TotalMatchesPlayed,
				&usfg.Stats.TotalMatchesWon,
				&usfg.Stats.TotalMatchesWonBaggage,
				&usfg.Stats.TotalMatchesWonBank,
				&usfg.Stats.TotalMatchesWonLake,
				&usfg.Stats.TotalMatchesWonSafehouse,
				&usfg.Stats.TotalMatchesWonShoots,
				&usfg.Stats.TotalMatchesWonStmarc,
				&usfg.Stats.TotalMatchesWonSugarcane,
				&usfg.Stats.TotalMatchesWonTrain,
				&usfg.Stats.TotalMoneyEarned,
				&usfg.Stats.TotalMvps,
				&usfg.Stats.TotalPlantedBombs,
				&usfg.Stats.TotalProgressiveMatchesWon,
				&usfg.Stats.TotalRescuedHostages,
				&usfg.Stats.TotalRevenges,
				&usfg.Stats.TotalRoundsMapArBaggage,
				&usfg.Stats.TotalRoundsMapArMonastery,
				&usfg.Stats.TotalRoundsMapArShoots,
				&usfg.Stats.TotalRoundsMapCsAssault,
				&usfg.Stats.TotalRoundsMapCsItaly,
				&usfg.Stats.TotalRoundsMapCsMilitia,
				&usfg.Stats.TotalRoundsMapCsOffice,
				&usfg.Stats.TotalRoundsMapDeAztec,
				&usfg.Stats.TotalRoundsMapDeBank,
				&usfg.Stats.TotalRoundsMapDeCbble,
				&usfg.Stats.TotalRoundsMapDeDust,
				&usfg.Stats.TotalRoundsMapDeDust2,
				&usfg.Stats.TotalRoundsMapDeInferno,
				&usfg.Stats.TotalRoundsMapDeLake,
				&usfg.Stats.TotalRoundsMapDeNuke,
				&usfg.Stats.TotalRoundsMapDeSafehouse,
				&usfg.Stats.TotalRoundsMapDeShorttrain,
				&usfg.Stats.TotalRoundsMapDeStmarc,
				&usfg.Stats.TotalRoundsMapDeSugarcane,
				&usfg.Stats.TotalRoundsMapDeTrain,
				&usfg.Stats.TotalRoundsMapDeVertigo,
				&usfg.Stats.TotalRoundsPlayed,
				&usfg.Stats.TotalShotsAk47,
				&usfg.Stats.TotalShotsAug,
				&usfg.Stats.TotalShotsAwp,
				&usfg.Stats.TotalShotsBizon,
				&usfg.Stats.TotalShotsDeagle,
				&usfg.Stats.TotalShotsElite,
				&usfg.Stats.TotalShotsFamas,
				&usfg.Stats.TotalShotsFired,
				&usfg.Stats.TotalShotsFiveseven,
				&usfg.Stats.TotalShotsG3sg1,
				&usfg.Stats.TotalShotsGalilar,
				&usfg.Stats.TotalShotsGlock,
				&usfg.Stats.TotalShotsHit,
				&usfg.Stats.TotalShotsHkp2000,
				&usfg.Stats.TotalShotsM249,
				&usfg.Stats.TotalShotsM4a1,
				&usfg.Stats.TotalShotsMac10,
				&usfg.Stats.TotalShotsMag7,
				&usfg.Stats.TotalShotsMp7,
				&usfg.Stats.TotalShotsMp9,
				&usfg.Stats.TotalShotsNegev,
				&usfg.Stats.TotalShotsNova,
				&usfg.Stats.TotalShotsP250,
				&usfg.Stats.TotalShotsP90,
				&usfg.Stats.TotalShotsSawedoff,
				&usfg.Stats.TotalShotsScar20,
				&usfg.Stats.TotalShotsSg556,
				&usfg.Stats.TotalShotsSsg08,
				&usfg.Stats.TotalShotsTaser,
				&usfg.Stats.TotalShotsTec9,
				&usfg.Stats.TotalShotsUmp45,
				&usfg.Stats.TotalShotsXm1014,
				&usfg.Stats.TotalTimePlayed,
				&usfg.Stats.TotalTrbombMatchesWon,
				&usfg.Stats.TotalTRDefusedBombs,
				&usfg.Stats.TotalTRPlantedBombs,
				&usfg.Stats.TotalWeaponsDonated,
				&usfg.Stats.TotalWins,
				&usfg.Stats.TotalWinsMapArBaggage,
				&usfg.Stats.TotalWinsMapArMonastery,
				&usfg.Stats.TotalWinsMapArShoots,
				&usfg.Stats.TotalWinsMapCsAssault,
				&usfg.Stats.TotalWinsMapCsItaly,
				&usfg.Stats.TotalWinsMapCsMilitia,
				&usfg.Stats.TotalWinsMapCsOffice,
				&usfg.Stats.TotalWinsMapDeAztec,
				&usfg.Stats.TotalWinsMapDeBank,
				&usfg.Stats.TotalWinsMapDeCbble,
				&usfg.Stats.TotalWinsMapDeDust,
				&usfg.Stats.TotalWinsMapDeDust2,
				&usfg.Stats.TotalWinsMapDeHouse,
				&usfg.Stats.TotalWinsMapDeInferno,
				&usfg.Stats.TotalWinsMapDeLake,
				&usfg.Stats.TotalWinsMapDeNuke,
				&usfg.Stats.TotalWinsMapDeSafehouse,
				&usfg.Stats.TotalWinsMapDeShorttrain,
				&usfg.Stats.TotalWinsMapDeStmarc,
				&usfg.Stats.TotalWinsMapDeSugarcane,
				&usfg.Stats.TotalWinsMapDeTrain,
				&usfg.Stats.TotalWinsMapDeVertigo,
				&usfg.Stats.TotalWinsPistolround,
			)
		}
	}
	return usfg, err
}

// UpdateUserStatsForGame receives a UserStatsForGame object and updates the
// corresponding entry in the database for the steamID
func (ds *DataStorage) UpdateUserStatsForGame(stats steamclient.UserStatsForGame) error {

	var result sql.Result
	var err error

	if result, err = ds.statements["update_player_stats"].Exec(
		stats.SteamID,
		stats.Stats.TotalKills,
		stats.Stats.TotalDeaths,
		stats.Stats.TotalTimePlayed,
		stats.Stats.TotalPlantedBombs,
		stats.Stats.TotalDefusedBombs,
		stats.Stats.TotalWins,
		stats.Stats.TotalDamageDone,
		stats.Stats.TotalMoneyEarned,
		stats.Stats.TotalKillsKnife,
		stats.Stats.TotalKillsHegrenade,
		stats.Stats.TotalKillsGlock,
		stats.Stats.TotalKillsDeagle,
		stats.Stats.TotalKillsElite,
		stats.Stats.TotalKillsFiveseven,
		stats.Stats.TotalKillsXm1014,
		stats.Stats.TotalKillsMac10,
		stats.Stats.TotalKillsUmp45,
		stats.Stats.TotalKillsP90,
		stats.Stats.TotalKillsAwp,
		stats.Stats.TotalKillsAk47,
		stats.Stats.TotalKillsAug,
		stats.Stats.TotalKillsFamas,
		stats.Stats.TotalKillsG3sg1,
		stats.Stats.TotalKillsM249,
		stats.Stats.TotalKillsHeadshot,
		stats.Stats.TotalKillsEnemyWeapon,
		stats.Stats.TotalWinsPistolround,
		stats.Stats.TotalWinsMapCsAssault,
		stats.Stats.TotalWinsMapDeDust2,
		stats.Stats.TotalWinsMapDeInferno,
		stats.Stats.TotalWinsMapDeTrain,
		stats.Stats.TotalWeaponsDonated,
		stats.Stats.TotalKillsEnemyBlinded,
		stats.Stats.TotalKillsKnifeFight,
		stats.Stats.TotalKillsAgainstZoomedSniper,
		stats.Stats.TotalDominations,
		stats.Stats.TotalDominationOverkills,
		stats.Stats.TotalRevenges,
		stats.Stats.TotalShotsHit,
		stats.Stats.TotalShotsFired,
		stats.Stats.TotalRoundsPlayed,
		stats.Stats.TotalShotsDeagle,
		stats.Stats.TotalShotsGlock,
		stats.Stats.TotalShotsElite,
		stats.Stats.TotalShotsFiveseven,
		stats.Stats.TotalShotsAwp,
		stats.Stats.TotalShotsAk47,
		stats.Stats.TotalShotsAug,
		stats.Stats.TotalShotsFamas,
		stats.Stats.TotalShotsG3sg1,
		stats.Stats.TotalShotsP90,
		stats.Stats.TotalShotsMac10,
		stats.Stats.TotalShotsUmp45,
		stats.Stats.TotalShotsXm1014,
		stats.Stats.TotalShotsM249,
		stats.Stats.TotalHitsDeagle,
		stats.Stats.TotalHitsGlock,
		stats.Stats.TotalHitsElite,
		stats.Stats.TotalHitsFiveseven,
		stats.Stats.TotalHitsAwp,
		stats.Stats.TotalHitsAk47,
		stats.Stats.TotalHitsAug,
		stats.Stats.TotalHitsFamas,
		stats.Stats.TotalHitsG3sg1,
		stats.Stats.TotalHitsP90,
		stats.Stats.TotalHitsMac10,
		stats.Stats.TotalHitsUmp45,
		stats.Stats.TotalHitsXm1014,
		stats.Stats.TotalHitsM249,
		stats.Stats.TotalRoundsMapCsAssault,
		stats.Stats.TotalRoundsMapDeDust2,
		stats.Stats.TotalRoundsMapDeInferno,
		stats.Stats.TotalRoundsMapDeTrain,
		stats.Stats.LastMatchTWins,
		stats.Stats.LastMatchCtWins,
		stats.Stats.LastMatchWins,
		stats.Stats.LastMatchMaxPlayers,
		stats.Stats.LastMatchKills,
		stats.Stats.LastMatchDeaths,
		stats.Stats.LastMatchMvps,
		stats.Stats.LastMatchFavweaponID,
		stats.Stats.LastMatchFavweaponShots,
		stats.Stats.LastMatchFavweaponHits,
		stats.Stats.LastMatchFavweaponKills,
		stats.Stats.LastMatchDamage,
		stats.Stats.LastMatchMoneySpent,
		stats.Stats.LastMatchDominations,
		stats.Stats.LastMatchRevenges,
		stats.Stats.TotalMvps,
		stats.Stats.TotalRoundsMapDeLake,
		stats.Stats.TotalRoundsMapDeSafehouse,
		stats.Stats.TotalRoundsMapDeBank,
		stats.Stats.TotalTRPlantedBombs,
		stats.Stats.TotalGunGameRoundsWon,
		stats.Stats.TotalGunGameRoundsPlayed,
		stats.Stats.TotalWinsMapDeBank,
		stats.Stats.TotalWinsMapDeLake,
		stats.Stats.TotalMatchesWonBank,
		stats.Stats.TotalMatchesWon,
		stats.Stats.TotalMatchesPlayed,
		stats.Stats.TotalGgMatchesWon,
		stats.Stats.TotalGgMatchesPlayed,
		stats.Stats.TotalProgressiveMatchesWon,
		stats.Stats.TotalTrbombMatchesWon,
		stats.Stats.TotalContributionScore,
		stats.Stats.LastMatchContributionScore,
		stats.Stats.LastMatchRounds,
		stats.Stats.TotalKillsHkp2000,
		stats.Stats.TotalShotsHkp2000,
		stats.Stats.TotalHitsHkp2000,
		stats.Stats.TotalHitsP250,
		stats.Stats.TotalKillsP250,
		stats.Stats.TotalShotsP250,
		stats.Stats.TotalKillsSg556,
		stats.Stats.TotalShotsSg556,
		stats.Stats.TotalHitsSg556,
		stats.Stats.TotalHitsScar20,
		stats.Stats.TotalKillsScar20,
		stats.Stats.TotalShotsScar20,
		stats.Stats.TotalShotsSsg08,
		stats.Stats.TotalHitsSsg08,
		stats.Stats.TotalKillsSsg08,
		stats.Stats.TotalShotsMp7,
		stats.Stats.TotalHitsMp7,
		stats.Stats.TotalKillsMp7,
		stats.Stats.TotalKillsMp9,
		stats.Stats.TotalShotsMp9,
		stats.Stats.TotalHitsMp9,
		stats.Stats.TotalHitsNova,
		stats.Stats.TotalKillsNova,
		stats.Stats.TotalShotsNova,
		stats.Stats.TotalHitsNegev,
		stats.Stats.TotalKillsNegev,
		stats.Stats.TotalShotsNegev,
		stats.Stats.TotalShotsSawedoff,
		stats.Stats.TotalHitsSawedoff,
		stats.Stats.TotalKillsSawedoff,
		stats.Stats.TotalShotsBizon,
		stats.Stats.TotalHitsBizon,
		stats.Stats.TotalKillsBizon,
		stats.Stats.TotalKillsTec9,
		stats.Stats.TotalShotsTec9,
		stats.Stats.TotalHitsTec9,
		stats.Stats.TotalShotsMag7,
		stats.Stats.TotalHitsMag7,
		stats.Stats.TotalKillsMag7,
		stats.Stats.TotalGunGameContributionScore,
		stats.Stats.LastMatchGgContributionScore,
		stats.Stats.TotalKillsM4a1,
		stats.Stats.TotalKillsGalilar,
		stats.Stats.TotalKillsMolotov,
		stats.Stats.TotalKillsTaser,
		stats.Stats.TotalShotsM4a1,
		stats.Stats.TotalShotsGalilar,
		stats.Stats.TotalShotsTaser,
		stats.Stats.TotalHitsM4a1,
		stats.Stats.TotalHitsGalilar,
		stats.Stats.TotalMatchesWonTrain,
		stats.Stats.TotalMatchesWonLake,
		stats.Stats.GILessonCsgoInstrExplainBuymenu,
		stats.Stats.GILessonCsgoInstrExplainBuyarmor,
		stats.Stats.GILessonCsgoInstrExplainPlantBomb,
		stats.Stats.GILessonCsgoInstrExplainBombCarrier,
		stats.Stats.GILessonBombSitesA,
		stats.Stats.GILessonDefusePlantedBomb,
		stats.Stats.GILessonCsgoInstrExplainFollowBomber,
		stats.Stats.GILessonCsgoInstrExplainPickupBomb,
		stats.Stats.GILessonCsgoInstrExplainPreventBombPickup,
		stats.Stats.GILessonCsgoCycleWeaponsKb,
		stats.Stats.GILessonCsgoInstrExplainZoom,
		stats.Stats.GILessonCsgoInstrExplainReload,
		stats.Stats.GILessonTrExplainPlantBomb,
		stats.Stats.GILessonBombSitesB,
		stats.Stats.GILessonVersionNumber,
		stats.Stats.GILessonFindPlantedBomb,
		stats.Stats.GILessonCsgoHostageLeadToHrz,
		stats.Stats.GILessonCsgoInstrRescueZone,
		stats.Stats.GILessonCsgoInstrExplainInspect,
		stats.Stats.SteamStatXpearnedgames,
	); err != nil {
		return err
	}

	rows, err := result.RowsAffected()
	log.Debugf("Added %v to player_stats table. %v rows affected", stats.SteamID, rows)

	if result, err = ds.statements["update_player_extra"].Exec(
		stats.SteamID,
		stats.Extra.TotalKD,
		stats.Extra.LastMatchKD,
		stats.Extra.HitRatio,
		stats.Extra.PlayedHours,
	); err != nil {
		return err
	}

	rows, err = result.RowsAffected()
	log.Debugf("Added %v to player_extra table. %v rows affected", stats.SteamID, rows)

	return err

}
