package main

// GameStats holds the players stats data from the steam API
// endpoint UserStatsForGame
type GameStats struct {
	GILessonCsgoInstrExplainInspect           string
	GILessonBombSitesA                        string
	GILessonBombSitesB                        string
	GILessonCsgoCycleWeaponsKb                string
	GILessonCsgoHostageLeadToHrz              string
	GILessonCsgoInstrExplainBombCarrier       string
	GILessonCsgoInstrExplainBuyarmor          string
	GILessonCsgoInstrExplainBuymenu           string
	GILessonCsgoInstrExplainFollowBomber      string
	GILessonCsgoInstrExplainPickupBomb        string
	GILessonCsgoInstrExplainPlantBomb         string
	GILessonCsgoInstrExplainPreventBombPickup string
	GILessonCsgoInstrExplainReload            string
	GILessonCsgoInstrExplainZoom              string
	GILessonCsgoInstrRescueZone               string
	GILessonDefusePlantedBomb                 string
	GILessonFindPlantedBomb                   string
	GILessonTrExplainPlantBomb                string
	GILessonVersionNumber                     string
	LastMatchContributionScore                string
	LastMatchCtWins                           string
	LastMatchDamage                           string
	LastMatchDeaths                           string
	LastMatchDominations                      string
	LastMatchFavweaponHits                    string
	LastMatchFavweaponID                      string
	LastMatchFavweaponKills                   string
	LastMatchFavweaponShots                   string
	LastMatchGgContributionScore              string
	LastMatchKills                            string
	LastMatchMaxPlayers                       string
	LastMatchMoneySpent                       string
	LastMatchMvps                             string
	LastMatchRevenges                         string
	LastMatchRounds                           string
	LastMatchTWins                            string
	LastMatchWins                             string
	SteamStatMatchwinscomp                    string
	SteamStatSurvivedz                        string
	SteamStatXpearnedgames                    string
	TotalBrokenWindows                        string
	TotalContributionScore                    string
	TotalDamageDone                           string
	TotalDeaths                               string
	TotalDefusedBombs                         string
	TotalDominationOverkills                  string
	TotalDominations                          string
	TotalGgMatchesPlayed                      string
	TotalGgMatchesWon                         string
	TotalGunGameContributionScore             string
	TotalGunGameRoundsPlayed                  string
	TotalGunGameRoundsWon                     string
	TotalHitsAk47                             string
	TotalHitsAug                              string
	TotalHitsAwp                              string
	TotalHitsBizon                            string
	TotalHitsDeagle                           string
	TotalHitsElite                            string
	TotalHitsFamas                            string
	TotalHitsFiveseven                        string
	TotalHitsG3sg1                            string
	TotalHitsGalilar                          string
	TotalHitsGlock                            string
	TotalHitsHkp2000                          string
	TotalHitsM249                             string
	TotalHitsM4a1                             string
	TotalHitsMac10                            string
	TotalHitsMag7                             string
	TotalHitsMp7                              string
	TotalHitsMp9                              string
	TotalHitsNegev                            string
	TotalHitsNova                             string
	TotalHitsP250                             string
	TotalHitsP90                              string
	TotalHitsSawedoff                         string
	TotalHitsScar20                           string
	TotalHitsSg556                            string
	TotalHitsSsg08                            string
	TotalHitsTec9                             string
	TotalHitsUmp45                            string
	TotalHitsXm1014                           string
	TotalKills                                string
	TotalKillsAgainstZoomedSniper             string
	TotalKillsAk47                            string
	TotalKillsAug                             string
	TotalKillsAwp                             string
	TotalKillsBizon                           string
	TotalKillsDeagle                          string
	TotalKillsElite                           string
	TotalKillsEnemyBlinded                    string
	TotalKillsEnemyWeapon                     string
	TotalKillsFamas                           string
	TotalKillsFiveseven                       string
	TotalKillsG3sg1                           string
	TotalKillsGalilar                         string
	TotalKillsGlock                           string
	TotalKillsHeadshot                        string
	TotalKillsHegrenade                       string
	TotalKillsHkp2000                         string
	TotalKillsKnife                           string
	TotalKillsKnifeFight                      string
	TotalKillsM249                            string
	TotalKillsM4a1                            string
	TotalKillsMac10                           string
	TotalKillsMag7                            string
	TotalKillsMolotov                         string
	TotalKillsMp7                             string
	TotalKillsMp9                             string
	TotalKillsNegev                           string
	TotalKillsNova                            string
	TotalKillsP250                            string
	TotalKillsP90                             string
	TotalKillsSawedoff                        string
	TotalKillsScar20                          string
	TotalKillsSg556                           string
	TotalKillsSsg08                           string
	TotalKillsTaser                           string
	TotalKillsTec9                            string
	TotalKillsUmp45                           string
	TotalKillsXm1014                          string
	TotalMatchesPlayed                        string
	TotalMatchesWon                           string
	TotalMatchesWonBaggage                    string
	TotalMatchesWonBank                       string
	TotalMatchesWonLake                       string
	TotalMatchesWonSafehouse                  string
	TotalMatchesWonShoots                     string
	TotalMatchesWonStmarc                     string
	TotalMatchesWonSugarcane                  string
	TotalMatchesWonTrain                      string
	TotalMoneyEarned                          string
	TotalMvps                                 string
	TotalPlantedBombs                         string
	TotalProgressiveMatchesWon                string
	TotalRescuedHostages                      string
	TotalRevenges                             string
	TotalRoundsMapArBaggage                   string
	TotalRoundsMapArMonastery                 string
	TotalRoundsMapArShoots                    string
	TotalRoundsMapCsAssault                   string
	TotalRoundsMapCsItaly                     string
	TotalRoundsMapCsMilitia                   string
	TotalRoundsMapCsOffice                    string
	TotalRoundsMapDeAztec                     string
	TotalRoundsMapDeBank                      string
	TotalRoundsMapDeCbble                     string
	TotalRoundsMapDeDust                      string
	TotalRoundsMapDeDust2                     string
	TotalRoundsMapDeInferno                   string
	TotalRoundsMapDeLake                      string
	TotalRoundsMapDeNuke                      string
	TotalRoundsMapDeSafehouse                 string
	TotalRoundsMapDeShorttrain                string
	TotalRoundsMapDeStmarc                    string
	TotalRoundsMapDeSugarcane                 string
	TotalRoundsMapDeTrain                     string
	TotalRoundsMapDeVertigo                   string
	TotalRoundsPlayed                         string
	TotalShotsAk47                            string
	TotalShotsAug                             string
	TotalShotsAwp                             string
	TotalShotsBizon                           string
	TotalShotsDeagle                          string
	TotalShotsElite                           string
	TotalShotsFamas                           string
	TotalShotsFired                           string
	TotalShotsFiveseven                       string
	TotalShotsG3sg1                           string
	TotalShotsGalilar                         string
	TotalShotsGlock                           string
	TotalShotsHit                             string
	TotalShotsHkp2000                         string
	TotalShotsM249                            string
	TotalShotsM4a1                            string
	TotalShotsMac10                           string
	TotalShotsMag7                            string
	TotalShotsMp7                             string
	TotalShotsMp9                             string
	TotalShotsNegev                           string
	TotalShotsNova                            string
	TotalShotsP250                            string
	TotalShotsP90                             string
	TotalShotsSawedoff                        string
	TotalShotsScar20                          string
	TotalShotsSg556                           string
	TotalShotsSsg08                           string
	TotalShotsTaser                           string
	TotalShotsTec9                            string
	TotalShotsUmp45                           string
	TotalShotsXm1014                          string
	TotalTRDefusedBombs                       string
	TotalTRPlantedBombs                       string
	TotalTimePlayed                           string
	TotalTrbombMatchesWon                     string
	TotalWeaponsDonated                       string
	TotalWins                                 string
	TotalWinsMapArBaggage                     string
	TotalWinsMapArMonastery                   string
	TotalWinsMapArShoots                      string
	TotalWinsMapCsAssault                     string
	TotalWinsMapCsItaly                       string
	TotalWinsMapCsMilitia                     string
	TotalWinsMapCsOffice                      string
	TotalWinsMapDeAztec                       string
	TotalWinsMapDeBank                        string
	TotalWinsMapDeCbble                       string
	TotalWinsMapDeDust                        string
	TotalWinsMapDeDust2                       string
	TotalWinsMapDeHouse                       string
	TotalWinsMapDeInferno                     string
	TotalWinsMapDeLake                        string
	TotalWinsMapDeNuke                        string
	TotalWinsMapDeSafehouse                   string
	TotalWinsMapDeShorttrain                  string
	TotalWinsMapDeStmarc                      string
	TotalWinsMapDeSugarcane                   string
	TotalWinsMapDeTrain                       string
	TotalWinsMapDeVertigo                     string
	TotalWinsPistolround                      string
}
